DROP TABLE IF EXISTS sensor_data;

CREATE TABLE sensor_data (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    speed TEXT NOT NULL,
    pressure TEXT NOT NULL,
    gyro TEXT NOT NULL
);